### PR TITLE
Allow attribs to work with the Namespace gem...

### PR DESCRIPTION
**Pull request by dennisfaust**
Changed the setter and getter to work like Redis::Objects because I'd like Attribs to use the Namespaced connection in a similar way to Redis::Objects. In my redis.rb I'm settting them like this:

$redis = Redis::Namespace.new("blah", redis: Redis.new(:host => uri.host, :port => uri.port, :password => uri.password))

Redis::Objects.redis = $redis
Redis::Attrs.redis   = $redis

### CODE REVIEW

**Comment by gnapse** [comment]
@dennisfaust this sounds like a nice addition to this gem. Thanks!

However, I would ask you a couple of things.
- Could you combine the 3 commits into a single one? It's because they're all pretty small and related, and the 2nd and 3rd commits both override a change made in the previous one, so it would be more clean to have all changes in a single step.
- I would appreciate if you would add a test case in `spec/redis_attrs_spec.rb` that would test the new functionality, making sure that values in Redis are being stored properly namespaced when a namespace is being used instead of a connection object.

In case you're in doubt, or don't have time, I can perform all these myself, and still give you credit for the original commit, but I'd prefer you doing it, since you came up with the idea.

**Comment by gnapse** [comment]
Forget about my requests. I can do that changes later on. Thanks again.

**Comment by dennisfaust** [comment]
Dear Ernesto,

```
I should have some time later this week and can do it then. Also, I'd
```

like to add handling for more meta data for each attribute. It would be
very useful to me to have a :default_value and a lambda that is stored with
the attribute that can be called to so it can update itself. In my case, I
have done something like that outside the gem. With those two pieces of
additional meta-data the gem could initialize and update the variables
which would be very handy. What do you think?

Thanks,

Dennis

dennis@dennisfaust.com
ph: 510.501.8771, skype: dffaust
http://www.linkedin.com/in/dennisfaust

**Comment by gnapse** [comment]
Hi Dennis,

All those suggested changes are welcome indeed! Please, let me know when you have it, via a pull request, and I can help too, if you want. I can do the tests for those features, for instance, after you implement it, or whatever.

**Comment by dennisfaust** [comment]
Dear Ernesto,

```
I'd be glad to have your help. Also, I've realized that I'm going to
```

need pipelining for performance reasons. Having a way to enumerate (and
then pipeline) all the attribs would be nice as well.

Thanks,

Dennis

dennis@dennisfaust.com
ph: 510.501.8771, skype: dffaust
http://www.linkedin.com/in/dennisfaust

**Comment by gnapse** [comment]
I'm sorry, I don't fully understand what you mean by enumerating and pipelining all the attribs.

Could you please open a couple different issues or pull-requests in the issue tracker? One for this enumerating and pipelining feature, and another one for the default_value/lambda stuff. So we can discuss each of these separately and in context?

I am really excited on this interest of yours in my gem, so please, give me all the info about what you need. Also, I have time now to devote to all this, but I won't have much time in about a month from now ;) Thanks!

**Pull request merged**
