### PR TITLE
Pipelining the redis.get of the scalar data types and returning defaults.

### PR DESCRIPTION
**Pull request by dennisfaust**
Dear Ernesto,

For performance reasons I need to pipeline the gets of all my values which happen to all be scalar. Since the complex data types present more issues I decided to wait and see what you thought about the idea, and my implementation before continuing. As you can see, I also hacked in default handling. This is a convenience for me so that I don't have to write a bunch of defensive code for nil checking. My application doesn't expect floats and integers to be nil. This small mod means I don't have to check them. Overall, I think you've done a great job with this gem and I'm just tweaking it for my particular case. If you like my changes and would like to include them, I'd be happy to write the readme changes as well.

### CODE REVIEW

**Comment by gnapse** [comment]
I implemented the "default values" feature independently in its own feature branch, you can take a look at it on the `develop` branch, and it will be included in the next release of the gem really soon. I developed it my self independently for various reasons, mainly because I like to implement different independent features on their own feature branch, but also because I wanted to implement it both for scalar and collection types. I also included a note in the README about how to use it.

As for the rest of the functionality that you need and implemented in this pull request, give me a day to study it to see what it is really about, and then I'll decide what to do with your pull request. It could help if you post here some info about the problem you're facing and the intended usage, to make it easier to understand the implementation you provided.

**Comment by dennisfaust** [comment]
Sure thing. My use case is the following: I have about 30 scalar values (integer and floats) I need to store for a number of users and groups. Performance with single keys is great as long as your redis server is local. I happened to test with a remote server and found the RTT was unacceptable when doing 30+ round trips frequently. I wanted a lightweight, pipelined method to set all my values and another to get them. Also, I created a meta-data driven library that is particular to my situation but the meta-data approach may interest you. If you have specific questions about my  implementation above I'd be happy to discuss it. I did the minimum to get my particular needs met and would be happy to contribute, I really like the concept and design of this gem.

**Comment by gnapse** [comment]
Hey @dennisfaust sorry about having left this unanswered. In hindsight the last time we spoke here was a complex time for me, and then I never came back to this when things settled down.

Is this gem still useful to you? Do these proposed changes still make sense? I'm not in the condition to resume working on this, but I'm more than happy to enable you to maintain it, or at least contribute this changes if it makes sense. Let me know.

**Comment by dennisfaust** [comment]
Dear Ernesto,

    Thanks for responding. I'm not working on the project any more and I'm
not in a position to take over maintenance of anything more at this point
either.

Thanks again,

Dennis

**Pull request closed without merging**
